name: React CI

on:
  push:
    branches:
      - "main"
      
jobs:
  build:
    runs-on: [ubuntu-latest, windows-latest, macOS-latest]
    strategy:
      matrix:
        node_version: ['18.x', '19.x']
        
        
    steps:
      - uses: actions/checkout@v1
      - run: npm install
      - run: npm run build
      - run: npm test
