name: workflow-1
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:      
      matrix:        
        node-version: [11.x]
    steps:         
      - name: Use Node.js ${{ matrix.node-version }}      
        uses: actions/setup-node@v1      
        with:        
          node-version: ${{ matrix.node-version }}
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Install packages
        run: |
          yarn install
      - name: Install packages
        run: |
          cd react-application-folder/
          yarn install
      - name: Production build      
        run: |        
          unset CI
          yarn build
      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_PRODUCTION_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: "build"
