name: React CI

on:
  push:
    branches:
      - "main"
      
  jobs:
    strategy:
      matrix:
        node_version: ['18.x', '19.x']
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v1
      - run: npm install
      - run: npm run build
      - run: npm test
